/*
  KCAreading book list.
  Add each Google Form URL inside formUrl when it is ready.
  Leave formUrl as an empty string to show “Coming soon”.
*/
window.BOOKS = [
  { year:"Nursery", title:"Monster Food", author:"Daisy Hirst", wholeClass:true, formUrl:"" , cover:"covers/book-01.webp" },
  { year:"Nursery", title:"The Rainbow Fish", author:"Marcus Pfister", formUrl:"" , cover:"covers/book-02.webp" },
  { year:"Nursery", title:"Alphonse, There's Mud on the Ceiling!", author:"Daisy Hirst", formUrl:"" , cover:"covers/book-03.webp" },
  { year:"Nursery", title:"Zeki Goes to the Park", author:"Anna McQuinn", formUrl:"" , cover:"covers/book-04.webp" },
  { year:"Nursery", title:"What Happened to You?", author:"James Catchpole", formUrl:"" , cover:"covers/book-05.webp" },
  { year:"Nursery", title:"We're Going on a Bear Hunt", author:"Michael Rosen", formUrl:"" , cover:"covers/book-06.webp" },
  { year:"Nursery", title:"Catch!", author:"Trish Cooke", formUrl:"" , cover:"covers/book-07.webp" },
  { year:"Nursery", title:"Where's Spot?", author:"Eric Hill", formUrl:"" , cover:"covers/book-08.webp" },
  { year:"Nursery", title:"Dear Zoo", author:"Rod Campbell", formUrl:"" , cover:"covers/book-09.webp" },
  { year:"Nursery", title:"The Very Hungry Caterpillar", author:"Eric Carle", wholeClass:true, formUrl:"" , cover:"covers/book-10.webp" },

  { year:"Reception", title:"The Gruffalo", author:"Julia Donaldson", formUrl:"" , cover:"covers/book-11.webp" },
  { year:"Reception", title:"Ready for Spaghetti", author:"Michael Rosen", wholeClass:true, formUrl:"" , cover:"covers/book-12.webp" },
  { year:"Reception", title:"So Much", author:"Trish Cooke", formUrl:"" , cover:"covers/book-13.webp" },
  { year:"Reception", title:"We're Going on a Lion Hunt", author:"David Axtell", formUrl:"" , cover:"covers/book-14.webp" },
  { year:"Reception", title:"All Are Welcome", author:"Alexandra Penfold", formUrl:"" , cover:"covers/book-15.webp" },
  { year:"Reception", title:"Flashlight", author:"Lizi Boyd", formUrl:"" , cover:"covers/book-16.webp" },
  { year:"Reception", title:"Oi Frog!", author:"Kes Gray", formUrl:"" , cover:"covers/book-17.webp" },
  { year:"Reception", title:"Martha Maps It Out", author:"Leigh Hodgkinson", formUrl:"" , cover:"covers/book-18.webp" },
  { year:"Reception", title:"Julian Is a Mermaid", author:"Jessica Love", formUrl:"" , cover:"covers/book-19.webp" },
  { year:"Reception", title:"The Perfect Sushi", author:"Emily Satoko Seo", wholeClass:true, formUrl:"" , cover:"covers/book-20.webp" },

  { year:"Year 1", title:"The Egg Box Dragon", author:"Richard Adams", wholeClass:true, formUrl:"" , cover:"covers/book-21.webp" },
  { year:"Year 1", title:"Shy", author:"Deborah Freedman", formUrl:"" , cover:"covers/book-22.webp" },
  { year:"Year 1", title:"The Lion Inside", author:"Rachel Bright", formUrl:"" , cover:"covers/book-23.webp" },
  { year:"Year 1", title:"Meesha Makes Friends", author:"Tom Percival", formUrl:"" , cover:"covers/book-24.webp" },
  { year:"Year 1", title:"Chocolate Cake", author:"Michael Rosen", formUrl:"" , cover:"covers/book-25.webp" },
  { year:"Year 1", title:"Terrible Horses", author:"Raymond Antrobus", formUrl:"" , cover:"covers/book-26.webp" },
  { year:"Year 1", title:"The Adventures of the Dish and the Spoon", author:"Mini Grey", formUrl:"" , cover:"covers/book-27.webp" },
  { year:"Year 1", title:"The Proudest Blue", author:"Ibtihaj Muhammad & S. K. Ali", formUrl:"" , cover:"covers/book-28.webp" },
  { year:"Year 1", title:"Funnybones", author:"Janet & Allan Ahlberg", formUrl:"" , cover:"covers/book-29.webp" },
  { year:"Year 1", title:"Love Grows Everywhere", author:"Barry Timms", wholeClass:true, formUrl:"" , cover:"covers/book-30.webp" },

  { year:"Year 2", title:"Look Up!", author:"Nathan Bryon", wholeClass:true, formUrl:"" , cover:"covers/book-31.webp" },
  { year:"Year 2", title:"Don't Look in This Book!", author:"Samuel Langley-Swain", formUrl:"" , cover:"covers/book-32.webp" },
  { year:"Year 2", title:"The Tear Thief", author:"Carol Ann Duffy", formUrl:"" , cover:"covers/book-33.webp" },
  { year:"Year 2", title:"Billy and the Beast", author:"Nadia Shireen", formUrl:"" , cover:"covers/book-34.webp" },
  { year:"Year 2", title:"The Kindest Red", author:"Ibtihaj Muhammad & S. K. Ali", formUrl:"" , cover:"covers/book-35.webp" },
  { year:"Year 2", title:"Our Tower", author:"Joseph Coelho", formUrl:"" , cover:"covers/book-36.webp" },
  { year:"Year 2", title:"Mr Wolf's Pancakes", author:"Jan Fearnley", formUrl:"" , cover:"covers/book-37.webp" },
  { year:"Year 2", title:"Bear and Bird: The Picnic", author:"Jarvis", formUrl:"" , cover:"covers/book-38.webp" },
  { year:"Year 2", title:"Flat Stanley", author:"Jeff Brown", formUrl:"" , cover:"covers/book-39.webp" },
  { year:"Year 2", title:"That Rabbit Belongs to Emily Brown", author:"Cressida Cowell", wholeClass:true, formUrl:"" , cover:"covers/book-40.webp" },

  { year:"Year 3", title:"A Walk in London", author:"Salvatore Rubbino", wholeClass:true, formUrl:"" , cover:"covers/book-41.webp" },
  { year:"Year 3", title:"Gorilla", author:"Anthony Browne", formUrl:"" , cover:"covers/book-42.webp" },
  { year:"Year 3", title:"The World According to Humphrey", author:"Betty G. Birney", formUrl:"" , cover:"covers/book-43.webp" },
  { year:"Year 3", title:"The Owl Who Was Afraid of the Dark", author:"Jill Tomlinson", formUrl:"" , cover:"covers/book-44.webp" },
  { year:"Year 3", title:"The Boy Who Grew Dragons", author:"Andy Shepherd", formUrl:"" , cover:"covers/book-45.webp" },
  { year:"Year 3", title:"Wild Magic: Legend of the Black Lion", author:"Abiola Bello", formUrl:"" , cover:"covers/book-46.webp" },
  { year:"Year 3", title:"The Nothing to See Here Hotel", author:"Steven Butler", formUrl:"" , cover:"covers/book-47.webp" },
  { year:"Year 3", title:"Pippi Longstocking", author:"Astrid Lindgren", formUrl:"" , cover:"covers/book-48.webp" },
  { year:"Year 3", title:"The Magic Finger", author:"Roald Dahl", formUrl:"" , cover:"covers/book-49.webp" },
  { year:"Year 3", title:"Stone Age Boy", author:"Satoshi Kitamura", wholeClass:true, formUrl:"" , cover:"covers/book-50.webp" },

  { year:"Year 4", title:"Charlie and the Chocolate Factory", author:"Roald Dahl", formUrl:"" , cover:"covers/book-51.webp" },
  { year:"Year 4", title:"Charlotte's Web", author:"E. B. White", wholeClass:true, formUrl:"" , cover:"covers/book-52.webp" },
  { year:"Year 4", title:"The Butterfly Lion", author:"Michael Morpurgo", formUrl:"" , cover:"covers/book-53.webp" },
  { year:"Year 4", title:"The Wonder Brothers", author:"Frank Cottrell-Boyce", formUrl:"" , cover:"covers/book-54.webp" },
  { year:"Year 4", title:"The Land of Roar", author:"Jenny McLachlan", formUrl:"" , cover:"covers/book-55.webp" },
  { year:"Year 4", title:"The Great Chocoplot", author:"Chris Callaghan", formUrl:"" , cover:"covers/book-56.webp" },
  { year:"Year 4", title:"Count", author:"Melvin Burgess", formUrl:"" , cover:"covers/book-57.webp" },
  { year:"Year 4", title:"The Hodgeheg", author:"Dick King-Smith", formUrl:"" , cover:"covers/book-58.webp" },
  { year:"Year 4", title:"The Boy at the Back of the Class", author:"Onjali Q. Raúf", wholeClass:true, formUrl:"" , cover:"covers/book-59.webp" },
  { year:"Year 4", title:"The Barnabus Project", author:"The Fan Brothers", formUrl:"" , cover:"covers/book-60.webp" },

  { year:"Year 5", title:"The Beast of Buckingham Palace", author:"David Walliams", formUrl:"https://docs.google.com/forms/d/e/1FAIpQLSfSGaOLq4fCKY_2iRMj8QoEzYL7PcFSW813SwGq2J2eqpb_PQ/viewform?usp=publish-editor" , cover:"covers/book-61.webp" },
  { year:"Year 5", title:"Lunar", author:"Chris Bradford", formUrl:"https://docs.google.com/forms/d/e/1FAIpQLSeL_26pUmPP9WPdHlOUCjbbS-YXmFlay3CRLNb1vW9gaWxeWA/viewform?usp=publish-editor" , cover:"covers/book-62.webp" },
  { year:"Year 5", title:"The Boy in the Tower", author:"Polly Ho-Yen", formUrl:"https://docs.google.com/forms/d/e/1FAIpQLSdFvxrRhPtwIWk0NriJfPep8Zw-UBADfXHNspWDeH-li28FLg/viewform?usp=publish-editor" , cover:"covers/book-63.webp" },
  { year:"Year 5", title:"The Factory Made Boy", author:"Christine Nöstlinger", formUrl:"https://docs.google.com/forms/d/e/1FAIpQLSccqaB5_DfZt1XipxoxD9iUDxqLlz3wwnsWe67w-i_B4pBH4g/viewform?usp=publish-editor" , cover:"covers/book-64.webp" },
  { year:"Year 5", title:"Edison", author:"Torben Kuhlmann", formUrl:"https://docs.google.com/forms/d/e/1FAIpQLSf5wv1eRBcJxb6FPFTWYj6GtqQp-aROvtzfOUEHUbVynAR2zw/viewform?usp=publish-editor" , cover:"covers/book-65.webp" },
  { year:"Year 5", title:"Cogheart", author:"Peter Bunzl", formUrl:"https://docs.google.com/forms/d/e/1FAIpQLSdJ8zjqucxP-i6cl31IiY9PsMVjsyEDMRQf6Xnv_RQJdEKupA/viewform?usp=publish-editor" , cover:"covers/book-66.webp" },
  { year:"Year 5", title:"Stig of the Dump", author:"Clive King", formUrl:"https://docs.google.com/forms/d/e/1FAIpQLSeqNz9Z59nS0K9-IgSjWq0vadk7StA1AqQIsIugs__y8WFCfQ/viewform?usp=publish-editor" , cover:"covers/book-67.webp" },
  { year:"Year 5", title:"The Firework-Maker's Daughter", author:"Philip Pullman", wholeClass:true, formUrl:"https://docs.google.com/forms/d/e/1FAIpQLSeRdJLnDXpGfmWNHftKSNkhOPM-Ew8ft1Abru-vFpdMB0qCSQ/viewform?usp=publish-editor" , cover:"covers/book-68.webp" },
  { year:"Year 5", title:"The Wild Robot", author:"Peter Brown", formUrl:"https://docs.google.com/forms/d/e/1FAIpQLSfZBnF3HX_T3k36kjNopsGT2OJlTDzeJsnehUziGMsBtMDfpg/viewform?usp=publish-editor" , cover:"covers/book-69.webp" },
  { year:"Year 5", title:"Diver's Daughter", author:"Patrice Lawrence", wholeClass:true, formUrl:"https://docs.google.com/forms/d/e/1FAIpQLSfMh8F_9iYTFynwfaL-i9I61qn2pSGgKecDYTdyJEwFv5ZGIQ/viewform?usp=publish-editor" , cover:"covers/book-70.webp" },

  { year:"Year 6", title:"The Boy Who Made Big Decisions", author:"Helen Rutter", formUrl:"https://docs.google.com/forms/d/e/1FAIpQLSd1p1pBo030hDc5ciaK-FgC4UkC1QxTZo5zQSc-OjceCZo-kQ/viewform?usp=dialog" , cover:"covers/book-71.webp" },
  { year:"Year 6", title:"The Nowhere Emporium", author:"Ross MacKenzie", formUrl:"https://docs.google.com/forms/d/e/1FAIpQLSerFjmoRX_PIdi6zemEU_UhgjBR24ibmSgnAOYyEmgu9yLFsA/viewform?usp=share_link&ouid=102874721147473405086" , cover:"covers/book-72.webp" },
  { year:"Year 6", title:"Windrush Child", author:"Benjamin Zephaniah", wholeClass:true, formUrl:"https://docs.google.com/forms/d/e/1FAIpQLSe8uXOZwyXM-XLkRXhm_tVXqDQTJNuQdyilcR_FU6_5jS5srA/viewform?usp=publish-editor" , cover:"covers/book-73.webp" },
  { year:"Year 6", title:"The Final Year", author:"Matt Goodfellow", formUrl:"https://docs.google.com/forms/d/e/1FAIpQLSePCsPdi3hr7s9onMLyr3QNd1mfb1eU_N3idyaUVtOc4XrhgA/viewform?usp=publish-editor" , cover:"covers/book-74.webp" },
  { year:"Year 6", title:"Storyland", author:"Amy Jeffs", formUrl:"https://docs.google.com/forms/d/e/1FAIpQLScLcrTceEoOqohw-lnqZNzqE6vJno-zgw16kIRbkBhBS8P5hw/viewform?usp=publish-editor" , cover:"covers/book-75.webp" },
  { year:"Year 6", title:"War Is Over", author:"David Almond", wholeClass:true, formUrl:"https://docs.google.com/forms/d/e/1FAIpQLSf8AcUN6x-srG2WeEfONPOHvEHKrsn4_q65ADuVCg7Z7Mcgpw/viewform?usp=publish-editor" , cover:"covers/book-76.webp" },
  { year:"Year 6", title:"Holes", author:"Louis Sachar", formUrl:"https://docs.google.com/forms/d/e/1FAIpQLScuvnwSEYqB9ICkQtGw5dLuCO8C16Sf8NEjg7k_DW1mI-tHnQ/viewform?usp=publish-editor" , cover:"covers/book-77.webp" },
  { year:"Year 6", title:"The London Eye Mystery", author:"Siobhan Dowd", formUrl:"https://docs.google.com/forms/d/e/1FAIpQLSdklkm-u1WmBaZZ-Y7uVzKSD4Qwcbu2GblXZIUXjxEBRDomug/viewform?usp=publish-editor" , cover:"covers/book-78.webp" },
  { year:"Year 6", title:"The Viewer", author:"Gary Crew & Shaun Tan", formUrl:"https://docs.google.com/forms/d/e/1FAIpQLSe1SyhKI7J7TG6h1sk3TLp5FAbWVT8AFrq89rx6dDYFRjHYZw/viewform?usp=publish-editor" , cover:"covers/book-79.webp" },
  { year:"Year 6", title:"The Ice Children", author:"M. G. Leonard", formUrl:"https://docs.google.com/forms/d/e/1FAIpQLSdq17PG8DbpNBk85tcjFxe5snVCZzJ0BbxEt9_LiATZx1zTwA/viewform?usp=publish-editor", cover:"covers/book-80.webp" }
];
