/*
  KCAreading book list.
  Add each Google Form URL inside formUrl when it is ready.
  Leave formUrl as an empty string to show “Coming soon”.
*/
window.BOOKS = [
  { year:"Nursery", title:"Monster Food", values:["Courage","Kindness"], author:"Daisy Hirst", wholeClass:true, formUrl:"" , cover:"covers/book-01.webp" },
  { year:"Nursery", title:"The Rainbow Fish", values:["Kindness","Respect"], author:"Marcus Pfister", formUrl:"" , cover:"covers/book-02.webp" },
  { year:"Nursery", title:"Alphonse, There's Mud on the Ceiling!", values:["Integrity","Kindness"], author:"Daisy Hirst", formUrl:"" , cover:"covers/book-03.webp" },
  { year:"Nursery", title:"Zeki Goes to the Park", values:["Respect","Kindness"], author:"Anna McQuinn", formUrl:"" , cover:"covers/book-04.webp" },
  { year:"Nursery", title:"What Happened to You?", values:["Respect","Kindness"], author:"James Catchpole", formUrl:"" , cover:"covers/book-05.webp" },
  { year:"Nursery", title:"We're Going on a Bear Hunt", values:["Courage","Endurance"], author:"Michael Rosen", formUrl:"" , cover:"covers/book-06.webp" },
  { year:"Nursery", title:"Catch!", values:["Kindness","Respect"], author:"Trish Cooke", formUrl:"" , cover:"covers/book-07.webp" },
  { year:"Nursery", title:"Where's Spot?", values:["Endurance"], author:"Eric Hill", formUrl:"" , cover:"covers/book-08.webp" },
  { year:"Nursery", title:"Dear Zoo", values:["Aspiration","Endurance"], author:"Rod Campbell", formUrl:"" , cover:"covers/book-09.webp" },
  { year:"Nursery", title:"The Very Hungry Caterpillar", values:["Endurance","Aspiration"], author:"Eric Carle", wholeClass:true, formUrl:"" , cover:"covers/book-10.webp" },

  { year:"Reception", title:"The Gruffalo", values:["Courage","Integrity"], author:"Julia Donaldson", formUrl:"" , cover:"covers/book-11.webp" },
  { year:"Reception", title:"Ready for Spaghetti", values:["Aspiration"], author:"Michael Rosen", wholeClass:true, formUrl:"" , cover:"covers/book-12.webp" },
  { year:"Reception", title:"So Much", values:["Kindness","Respect"], author:"Trish Cooke", formUrl:"" , cover:"covers/book-13.webp" },
  { year:"Reception", title:"We're Going on a Lion Hunt", values:["Courage","Endurance"], author:"David Axtell", formUrl:"" , cover:"covers/book-14.webp" },
  { year:"Reception", title:"All Are Welcome", values:["Respect","Kindness"], author:"Alexandra Penfold", formUrl:"" , cover:"covers/book-15.webp" },
  { year:"Reception", title:"Flashlight", values:["Courage"], author:"Lizi Boyd", formUrl:"" , cover:"covers/book-16.webp" },
  { year:"Reception", title:"Oi Frog!", values:["Respect","Integrity"], author:"Kes Gray", formUrl:"" , cover:"covers/book-17.webp" },
  { year:"Reception", title:"Martha Maps It Out", values:["Aspiration","Endurance"], author:"Leigh Hodgkinson", formUrl:"" , cover:"covers/book-18.webp" },
  { year:"Reception", title:"Julian Is a Mermaid", values:["Courage","Integrity"], author:"Jessica Love", formUrl:"" , cover:"covers/book-19.webp" },
  { year:"Reception", title:"The Perfect Sushi", values:["Aspiration","Endurance"], author:"Emily Satoko Seo", wholeClass:true, formUrl:"" , cover:"covers/book-20.webp" },

  { year:"Year 1", title:"The Egg Box Dragon", values:["Aspiration","Kindness"], author:"Richard Adams", wholeClass:true, formUrl:"" , cover:"covers/book-21.webp" },
  { year:"Year 1", title:"Shy", values:["Courage","Kindness"], author:"Deborah Freedman", formUrl:"" , cover:"covers/book-22.webp" },
  { year:"Year 1", title:"The Lion Inside", values:["Courage","Aspiration"], author:"Rachel Bright", formUrl:"" , cover:"covers/book-23.webp" },
  { year:"Year 1", title:"Meesha Makes Friends", values:["Kindness","Courage"], author:"Tom Percival", formUrl:"" , cover:"covers/book-24.webp" },
  { year:"Year 1", title:"Chocolate Cake", values:["Integrity"], author:"Michael Rosen", formUrl:"" , cover:"covers/book-25.webp" },
  { year:"Year 1", title:"Terrible Horses", values:["Courage","Endurance"], author:"Raymond Antrobus", formUrl:"" , cover:"covers/book-26.webp" },
  { year:"Year 1", title:"The Adventures of the Dish and the Spoon", values:["Integrity","Kindness"], author:"Mini Grey", formUrl:"" , cover:"covers/book-27.webp" },
  { year:"Year 1", title:"The Proudest Blue", values:["Courage","Respect"], author:"Ibtihaj Muhammad & S. K. Ali", formUrl:"" , cover:"covers/book-28.webp" },
  { year:"Year 1", title:"Funnybones", values:["Courage"], author:"Janet & Allan Ahlberg", formUrl:"" , cover:"covers/book-29.webp" },
  { year:"Year 1", title:"Love Grows Everywhere", values:["Kindness","Respect"], author:"Barry Timms", wholeClass:true, formUrl:"" , cover:"covers/book-30.webp" },

  { year:"Year 2", title:"Look Up!", values:["Aspiration","Endurance"], author:"Nathan Bryon", wholeClass:true, formUrl:"" , cover:"covers/book-31.webp" },
  { year:"Year 2", title:"Don't Look in This Book!", values:["Courage","Integrity"], author:"Samuel Langley-Swain", formUrl:"" , cover:"covers/book-32.webp" },
  { year:"Year 2", title:"The Tear Thief", values:["Kindness","Courage"], author:"Carol Ann Duffy", formUrl:"" , cover:"covers/book-33.webp" },
  { year:"Year 2", title:"Billy and the Beast", values:["Courage","Aspiration"], author:"Nadia Shireen", formUrl:"" , cover:"covers/book-34.webp" },
  { year:"Year 2", title:"The Kindest Red", values:["Kindness","Respect"], author:"Ibtihaj Muhammad & S. K. Ali", formUrl:"" , cover:"covers/book-35.webp" },
  { year:"Year 2", title:"Our Tower", values:["Aspiration","Respect"], author:"Joseph Coelho", formUrl:"" , cover:"covers/book-36.webp" },
  { year:"Year 2", title:"Mr Wolf's Pancakes", values:["Integrity","Kindness"], author:"Jan Fearnley", formUrl:"" , cover:"covers/book-37.webp" },
  { year:"Year 2", title:"Bear and Bird: The Picnic", values:["Kindness","Respect"], author:"Jarvis", formUrl:"" , cover:"covers/book-38.webp" },
  { year:"Year 2", title:"Flat Stanley", values:["Courage","Endurance"], author:"Jeff Brown", formUrl:"" , cover:"covers/book-39.webp" },
  { year:"Year 2", title:"That Rabbit Belongs to Emily Brown", values:["Courage","Integrity"], author:"Cressida Cowell", wholeClass:true, formUrl:"" , cover:"covers/book-40.webp" },

  { year:"Year 3", title:"A Walk in London", values:["Aspiration","Respect"], author:"Salvatore Rubbino", wholeClass:true, formUrl:"" , cover:"covers/book-41.webp" },
  { year:"Year 3", title:"Gorilla", values:["Kindness","Respect"], author:"Anthony Browne", formUrl:"" , cover:"covers/book-42.webp" },
  { year:"Year 3", title:"The World According to Humphrey", values:["Kindness","Integrity"], author:"Betty G. Birney", formUrl:"" , cover:"covers/book-43.webp" },
  { year:"Year 3", title:"The Owl Who Was Afraid of the Dark", values:["Courage","Endurance"], author:"Jill Tomlinson", formUrl:"" , cover:"covers/book-44.webp" },
  { year:"Year 3", title:"The Boy Who Grew Dragons", values:["Aspiration","Endurance"], author:"Andy Shepherd", formUrl:"" , cover:"covers/book-45.webp" },
  { year:"Year 3", title:"Wild Magic: Legend of the Black Lion", values:["Courage","Integrity"], author:"Abiola Bello", formUrl:"" , cover:"covers/book-46.webp" },
  { year:"Year 3", title:"The Nothing to See Here Hotel", values:["Courage","Kindness"], author:"Steven Butler", formUrl:"" , cover:"covers/book-47.webp" },
  { year:"Year 3", title:"Pippi Longstocking", values:["Courage","Aspiration"], author:"Astrid Lindgren", formUrl:"" , cover:"covers/book-48.webp" },
  { year:"Year 3", title:"The Magic Finger", values:["Integrity","Respect"], author:"Roald Dahl", formUrl:"" , cover:"covers/book-49.webp" },
  { year:"Year 3", title:"Stone Age Boy", values:["Courage","Respect"], author:"Satoshi Kitamura", wholeClass:true, formUrl:"" , cover:"covers/book-50.webp" },

  { year:"Year 4", title:"Charlie and the Chocolate Factory", values:["Aspiration","Integrity"], author:"Roald Dahl", formUrl:"" , cover:"covers/book-51.webp" },
  { year:"Year 4", title:"Charlotte's Web", values:["Kindness","Endurance"], author:"E. B. White", wholeClass:true, formUrl:"" , cover:"covers/book-52.webp" },
  { year:"Year 4", title:"The Butterfly Lion", values:["Kindness","Courage"], author:"Michael Morpurgo", formUrl:"" , cover:"covers/book-53.webp" },
  { year:"Year 4", title:"The Wonder Brothers", values:["Aspiration","Endurance"], author:"Frank Cottrell-Boyce", formUrl:"" , cover:"covers/book-54.webp" },
  { year:"Year 4", title:"The Land of Roar", values:["Courage","Aspiration"], author:"Jenny McLachlan", formUrl:"" , cover:"covers/book-55.webp" },
  { year:"Year 4", title:"The Great Chocoplot", values:["Endurance","Integrity"], author:"Chris Callaghan", formUrl:"" , cover:"covers/book-56.webp" },
  { year:"Year 4", title:"Count", values:["Aspiration","Endurance"], author:"Melvin Burgess", formUrl:"" , cover:"covers/book-57.webp" },
  { year:"Year 4", title:"The Hodgeheg", values:["Endurance","Courage"], author:"Dick King-Smith", formUrl:"" , cover:"covers/book-58.webp" },
  { year:"Year 4", title:"The Boy at the Back of the Class", values:["Kindness","Respect"], author:"Onjali Q. Raúf", wholeClass:true, formUrl:"" , cover:"covers/book-59.webp" },
  { year:"Year 4", title:"The Barnabus Project", values:["Courage","Integrity"], author:"The Fan Brothers", formUrl:"" , cover:"covers/book-60.webp" },

  { year:"Year 5", title:"The Beast of Buckingham Palace", values:["Courage","Integrity"], author:"David Walliams", formUrl:"" , cover:"covers/book-61.webp" },
  { year:"Year 5", title:"Lunar", values:["Aspiration","Endurance"], author:"Chris Bradford", formUrl:"" , cover:"covers/book-62.webp" },
  { year:"Year 5", title:"The Boy in the Tower", values:["Courage","Endurance"], author:"Polly Ho-Yen", formUrl:"" , cover:"covers/book-63.webp" },
  { year:"Year 5", title:"The Factory Made Boy", values:["Integrity","Courage"], author:"Christine Nöstlinger", formUrl:"" , cover:"covers/book-64.webp" },
  { year:"Year 5", title:"Edison", values:["Aspiration","Endurance"], author:"Torben Kuhlmann", formUrl:"" , cover:"covers/book-65.webp" },
  { year:"Year 5", title:"Cogheart", values:["Courage","Integrity"], author:"Peter Bunzl", formUrl:"" , cover:"covers/book-66.webp" },
  { year:"Year 5", title:"Stig of the Dump", values:["Kindness","Respect"], author:"Clive King", formUrl:"" , cover:"covers/book-67.webp" },
  { year:"Year 5", title:"The Firework-Maker's Daughter", values:["Aspiration","Courage"], author:"Philip Pullman", wholeClass:true, formUrl:"" , cover:"covers/book-68.webp" },
  { year:"Year 5", title:"The Wild Robot", values:["Kindness","Endurance"], author:"Peter Brown", formUrl:"" , cover:"covers/book-69.webp" },
  { year:"Year 5", title:"Diver's Daughter", values:["Courage","Aspiration"], author:"Patrice Lawrence", wholeClass:true, formUrl:"" , cover:"covers/book-70.webp" },

  { year:"Year 6", title:"The Boy Who Made Big Decisions", values:["Integrity","Courage"], author:"Helen Rutter", formUrl:"" , cover:"covers/book-71.webp" },
  { year:"Year 6", title:"The Nowhere Emporium", values:["Courage","Aspiration"], author:"Ross MacKenzie", formUrl:"" , cover:"covers/book-72.webp" },
  { year:"Year 6", title:"Windrush Child", values:["Courage","Endurance","Respect"], author:"Benjamin Zephaniah", wholeClass:true, formUrl:"" , cover:"covers/book-73.webp" },
  { year:"Year 6", title:"The Final Year", values:["Endurance","Kindness"], author:"Matt Goodfellow", formUrl:"" , cover:"covers/book-74.webp" },
  { year:"Year 6", title:"Storyland", values:["Aspiration","Respect"], author:"Amy Jeffs", formUrl:"" , cover:"covers/book-75.webp" },
  { year:"Year 6", title:"War Is Over", values:["Kindness","Integrity"], author:"David Almond", wholeClass:true, formUrl:"" , cover:"covers/book-76.webp" },
  { year:"Year 6", title:"Holes", values:["Endurance","Integrity"], author:"Louis Sachar", formUrl:"" , cover:"covers/book-77.webp" },
  { year:"Year 6", title:"The London Eye Mystery", values:["Endurance","Aspiration"], author:"Siobhan Dowd", formUrl:"" , cover:"covers/book-78.webp" },
  { year:"Year 6", title:"The Viewer", values:["Courage","Integrity"], author:"Gary Crew & Shaun Tan", formUrl:"" , cover:"covers/book-79.webp" },
  { year:"Year 6", title:"The Ice Children", values:["Courage","Endurance"], author:"M. G. Leonard", formUrl:"", cover:"covers/book-80.webp" }
];
